# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: loghourAPI

package:
  exclude:
    - node_modules/serverless-offline/**

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  stage: dev

plugins:
  - serverless-offline
  - serverless-plugin-write-env-vars

custom:
  stage: ${opt:stage, self:provider.stage}
  client_secret: ${opt:client_secret, self:provider.client_secret}
  client_id: ${opt:client_id, self:provider.client_id}
  writeEnvVars:
    REMOTE_STAGE: ${self:custom.stage}
    GITHUB_CLIENT_SECRET: ${self:custom.client_secret}
    GITHUB_CLIENT_ID: ${self:custom.client_id}

functions:
  authorize:
    handler: handlers/authorize/index.handler
    events:
      - http:
          method: GET
          path: authorize/{code}
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
